# Generated by Django 5.0.1 on 2025-11-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0003_alter_costumer_social_media'),
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to='costumers.costumer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.CharField(max_length=100, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
