# Generated by Django 5.0.1 on 2025-11-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_outflow_costumer_outflow_value_and_more'),
        ('products', '0004_product_name_product_stock_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total'),
        ),
    ]
